### ISSUE TITLE
Peak Nits of Display?

### ISSUE THREAD

**Issue by pbiancardi** [natural-harmonia-gropius/hdr-toys#27]
Should I be entering the peak nits of my display (120) somewhere in the mpv.conf?

I do this for MadVR but not sure how to handle with HDR Toys?

**Comment by danbezerra** [comment]
Not the developer, but I believe you should add the following line to your config file:
glsl-shader-opts-add=L_sdr=100

**Comment by natural-harmonia-gropius** [comment]
> glsl-shader-opts-add=L_sdr=120

This is.

---

My opinion is to use the reference white instead of the peak white of display, that when you are watching a SDR content the white always be show as peak, but it's 100nit or 203nit in grading works. From more specific point, when you use OBS to capture the SDR screen, the white is default to 203nit, if you set L_sdr as 100nit, they get overexposured.
