### ISSUE TITLE
Histogram based curve

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [natural-harmonia-gropius/hdr-toys#5]
Maybe something like this.

![屏幕截图 2022-12-16 200543](https://user-images.githubusercontent.com/50797982/218965995-7a1f0a37-1d38-41b2-9608-3a9d964143f4.jpg)

**Comment by natural-harmonia-gropius** [comment]
I'm really curious if I can get good results with a statistical curve?

**Trash Talk** 

![image](https://user-images.githubusercontent.com/50797982/225710888-3e88ea46-ce87-418c-a7bd-2ed6fdb36ddf.png)
The.Meg 00:58:01 with `tone-mapping/linear` and `L_hdr=2100`

Looks pretty good, right? But it doesn't mean I should do something like this. It means the grading of this frame is piece of shit, it does not match either human perception or the mechanical response of camera.

Everyone should take a look at this:
https://www.youtube.com/watch?v=8rKyPCrijCY

**Comment by danbezerra** [comment]
Yeah, The Meg is known for its complicated grading ... There are a few other titles as well (latest MadMax, Batman vs Superman,...). In my opinion, the effort to support corner cases like this one needs to be balanced with:
- Is it damaging other situations, or can you keep the overall quality while also improving challenging scenes?
- Could your time be spent on other issues that are more common/would improve the overall quality of HDR movies?

MadVR for example is spending months mainly on the fine tuning of their HDR solution - mostly focusing on such trick scenes.  One could argue that DV support, local tone mapping and other HDR improvements should come first. But they often get a positive review when compared with other tone mapping solutions - since tricky scenes are often used in the comparison.

**Comment by danbezerra** [comment]
It seems that histogram based tonemapping is now part of libplacebo. Would you be able to use it or you need a different implementation?

https://code.videolan.org/videolan/libplacebo/-/tags/v5.264.0

**Comment by natural-harmonia-gropius** [comment]
I have to implement it on my own.

**Comment by natural-harmonia-gropius** [comment]
Move to https://github.com/natural-harmonia-gropius/hdr-toys/issues/7
